#AntTweakBar (without X11 support)
ATB_STATIC := /home/kdl/projects/anttweakbar/atb_osx_lean/lib/atb.a
ATB_INCLUDE:= /home/kdl/projects/anttweakbar/atb_osx_lean/include

#GLFW; includes use GL/glfw.h, which is default on linux.
GLFW_STATIC:= /usr/lib/libglfw.a
GLFW_INCLUDE:=  

#GTEST
GTEST_STATIC:=/home/kdl/projects/gtest/gtest-1.1.0/lib/.libs/libgtest_main.a /home/kdl/projects/gtest/gtest-1.1.0/lib/.libs/libgtest.a 
GTEST_INCLUDE:=/home/kdl/projects/gtest/gtest-1.1.0/include


LINKFLAGS := -lGL -lGLU -lXrandr -lz
CXXFLAGS := -DLINUX

-include Makefile